<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD1gCLpm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD1gCLpm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerD1gCLpm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerD1gCLpm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerD1gCLpm\App_KernelDevDebugContainer([
    'container.build_hash' => 'D1gCLpm',
    'container.build_id' => '6463d87a',
    'container.build_time' => 1597741893,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerD1gCLpm');
